# Generated by Django 3.2.7 on 2021-09-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0003_customuser_friendship_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
