# Generated by Django 3.2.7 on 2021-09-29 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recommender', '0004_auto_20210929_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('personality_type', models.PositiveSmallIntegerField(choices=[(1, 'ENFJ'), (2, 'ENFP'), (3, 'ENTJ'), (4, 'ENTP'), (5, 'ESFJ'), (6, 'ESFP'), (7, 'ESTJ'), (8, 'ESTP'), (9, 'INFJ'), (10, 'INFP'), (11, 'INTJ'), (12, 'INTP'), (13, 'ISFJ'), (14, 'ISFP'), (15, 'ISTJ'), (16, 'ISTP')])),
            ],
            options={
                'verbose_name_plural': 'CustomUsers',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('cleaned_post', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Recommender.customuser')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='friend', to='Recommender.customuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Recommender.customuser')),
            ],
            options={
                'verbose_name_plural': 'Friendships',
            },
        ),
    ]
