# Generated by Django 3.2.7 on 2021-10-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0005_customuser_friendship_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='predicted_personality',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ENFJ'), (2, 'ENFP'), (3, 'ENTJ'), (4, 'ENTP'), (5, 'ESFJ'), (6, 'ESFP'), (7, 'ESTJ'), (8, 'ESTP'), (9, 'INFJ'), (10, 'INFP'), (11, 'INTJ'), (12, 'INTP'), (13, 'ISFJ'), (14, 'ISFP'), (15, 'ISTJ'), (16, 'ISTP')], default=1),
        ),
    ]
