# Generated by Django 3.2.7 on 2021-10-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0006_customuser_predicted_personality'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tags of Interest',
            },
        ),
    ]
