# Generated by Django 3.2.7 on 2021-10-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0007_tagsofinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterestTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag', to='Recommender.tagsofinterest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Recommender.customuser')),
            ],
            options={
                'verbose_name_plural': 'User Interest Tags',
            },
        ),
    ]
